CC = g++
FLAGS = -std=c++11 -w -O2 -Wextra -Wall -Werror -Wno-sign-compare -Wno-unused-result -pedantic -lm
FILES = main.cpp
PROG = solution

all: da1

da1:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o solution
